[project]
name = "spark-delta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "delta-spark==2.4.0",
    "jupyterlab>=4.2.5",
    "pyspark==3.4.0",
]
